### ISSUE TITLE
Use "bundled" SDL2 feature

### ISSUE THREAD

**Issue by johnthagen** [PistonDevelopers/music#74]
If we use https://github.com/Rust-SDL2/rust-sdl2#bundled-feature, then users won't need to install SDL2 out of band, which would be a big usability bump.

This can't be completed until `'mixer'` is also bundled: https://github.com/Rust-SDL2/rust-sdl2/issues/778

**Comment by johnthagen** [comment]
For future reference, the updated `Cargo.toml` would look something like:

```toml
[dependencies.sdl2]
version = "0.31.0"
default-features = false
features = ["bundled", "mixer"]
```
